name: 'TawhidLinks!'
favicon: null
layout_spectrum: 0.74806
typography_spectrum: 0.50159
title: 'TawhidLinks!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#515151'
    - '#c9ab63'
    - '#01a2e6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
