typography_spectrum: 0.50159
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#515151'
    - '#c9ab63'
    - '#01a2e6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: TawhidLinks!
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: TawhidLinks!
purpose: []
