name: 'TawhidFirst!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7557403300888836
title: 'TawhidFirst!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#515151'
    - '#c9ab63'
    - '#01a2e6'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
