name: 'TawhidLinks!'
favicon: null
layout_spectrum: 0.981
typography_spectrum: 0.99087
title: 'TawhidLinks!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#515151'
    - '#c9ab63'
    - '#01a2e6'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
